{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg6\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib\n",
      "  Referenced from: <8354F308-2D0D-3C05-9D4E-3D4C3327D784> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.58.dylib' (no such file), '/usr/local/lib/libavutil.58.dylib' (no such file), '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg5\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib\n",
      "  Referenced from: <20585EA1-54CF-3A7A-911E-10CCE25B31B1> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.57.dylib' (no such file), '/usr/local/lib/libavutil.57.dylib' (no such file), '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg4\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib\n",
      "  Referenced from: <3B5A8336-9CE3-36F7-9A02-C2D6D54842BB> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.56.dylib' (no such file), '/usr/local/lib/libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 106, in _find_versionsed_ffmpeg_extension\n",
      "    raise RuntimeError(f\"FFmpeg{version} extension is not available.\")\n",
      "RuntimeError: FFmpeg extension is not available.\n"
     ]
    }
   ],
   "source": [
    "from validate import ZeroShotCallback\n",
    "from multimodal_data2vec import KDMMData2Vec, KDMMData2VecConfig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from datamodules import IMDBDataModule, SpeechCommandsDataModule, CIFARDataModule"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "ds = SpeechCommandsDataModule(data_path='../data',\n",
    "                              min_sample_size=0,\n",
    "                              normalize=True,\n",
    "                              pad=True,\n",
    "                              batch_size=512,\n",
    "                              num_workers=5,\n",
    "                              shuffle=False,\n",
    "                              drop_last=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "callback = ZeroShotCallback(n_neighbors=20, datamodules={'imdb': ds}, data_path='../data',\n",
    "                            num_max_bpe_tokens=512, is_multimodal_aligned=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "cfg = KDMMData2VecConfig(\n",
    "    depth=1,\n",
    "    num_heads=12,\n",
    "    mlp_ratio=0.1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:multimodal_data2vec:Loading modality encoder for: Modality.AUDIO\n",
      "INFO:utils:Modality used: Modality.AUDIO\n",
      "INFO:data2vec_fairseq.models.data2vec2:making target model\n",
      "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/nn/modules/module.py:1877: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.\n",
      "  warnings.warn(\n",
      "INFO:utils:Loaded state dict, result: <All keys matched successfully>\n",
      "INFO:multimodal_data2vec:Loading modality encoder for: Modality.IMAGE\n",
      "INFO:utils:Modality used: Modality.IMAGE\n",
      "INFO:data2vec_fairseq.models.data2vec2:making target model\n",
      "INFO:utils:Loaded state dict, result: <All keys matched successfully>\n",
      "INFO:multimodal_data2vec:Loading modality encoder for: Modality.TEXT\n",
      "INFO:utils:Modality used: Modality.TEXT\n",
      "INFO:data2vec_fairseq.models.data2vec2:making target model\n",
      "INFO:utils:Loaded state dict, result: <All keys matched successfully>\n"
     ]
    }
   ],
   "source": [
    "model = KDMMData2Vec(cfg=cfg)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from types import SimpleNamespace\n",
    "d = {'model': model, 'device':'cpu'}\n",
    "pl_module =  SimpleNamespace(**d)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEBUG:torio._extension.utils:Loading FFmpeg6\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib\n",
      "  Referenced from: <8354F308-2D0D-3C05-9D4E-3D4C3327D784> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.58.dylib' (no such file), '/usr/local/lib/libavutil.58.dylib' (no such file), '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg5\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib\n",
      "  Referenced from: <20585EA1-54CF-3A7A-911E-10CCE25B31B1> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.57.dylib' (no such file), '/usr/local/lib/libavutil.57.dylib' (no such file), '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg4\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib\n",
      "  Referenced from: <3B5A8336-9CE3-36F7-9A02-C2D6D54842BB> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.56.dylib' (no such file), '/usr/local/lib/libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 106, in _find_versionsed_ffmpeg_extension\n",
      "    raise RuntimeError(f\"FFmpeg{version} extension is not available.\")\n",
      "RuntimeError: FFmpeg extension is not available.\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg6\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib\n",
      "  Referenced from: <8354F308-2D0D-3C05-9D4E-3D4C3327D784> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.58.dylib' (no such file), '/usr/local/lib/libavutil.58.dylib' (no such file), '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg5\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib\n",
      "  Referenced from: <20585EA1-54CF-3A7A-911E-10CCE25B31B1> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.57.dylib' (no such file), '/usr/local/lib/libavutil.57.dylib' (no such file), '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg4\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib\n",
      "  Referenced from: <3B5A8336-9CE3-36F7-9A02-C2D6D54842BB> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.56.dylib' (no such file), '/usr/local/lib/libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 106, in _find_versionsed_ffmpeg_extension\n",
      "    raise RuntimeError(f\"FFmpeg{version} extension is not available.\")\n",
      "RuntimeError: FFmpeg extension is not available.\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg6\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib\n",
      "  Referenced from: <8354F308-2D0D-3C05-9D4E-3D4C3327D784> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.58.dylib' (no such file), '/usr/local/lib/libavutil.58.dylib' (no such file), '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg5\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib\n",
      "  Referenced from: <20585EA1-54CF-3A7A-911E-10CCE25B31B1> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.57.dylib' (no such file), '/usr/local/lib/libavutil.57.dylib' (no such file), '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg4\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib\n",
      "  Referenced from: <3B5A8336-9CE3-36F7-9A02-C2D6D54842BB> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.56.dylib' (no such file), '/usr/local/lib/libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 106, in _find_versionsed_ffmpeg_extension\n",
      "    raise RuntimeError(f\"FFmpeg{version} extension is not available.\")\n",
      "RuntimeError: FFmpeg extension is not available.\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg6\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib\n",
      "  Referenced from: <8354F308-2D0D-3C05-9D4E-3D4C3327D784> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.58.dylib' (no such file), '/usr/local/lib/libavutil.58.dylib' (no such file), '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg5\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib\n",
      "  Referenced from: <20585EA1-54CF-3A7A-911E-10CCE25B31B1> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.57.dylib' (no such file), '/usr/local/lib/libavutil.57.dylib' (no such file), '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg4\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib\n",
      "  Referenced from: <3B5A8336-9CE3-36F7-9A02-C2D6D54842BB> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.56.dylib' (no such file), '/usr/local/lib/libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 106, in _find_versionsed_ffmpeg_extension\n",
      "    raise RuntimeError(f\"FFmpeg{version} extension is not available.\")\n",
      "RuntimeError: FFmpeg extension is not available.\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg6\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib\n",
      "  Referenced from: <8354F308-2D0D-3C05-9D4E-3D4C3327D784> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.58.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.58.dylib' (no such file), '/usr/local/lib/libavutil.58.dylib' (no such file), '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg5\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib\n",
      "  Referenced from: <20585EA1-54CF-3A7A-911E-10CCE25B31B1> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.57.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.57.dylib' (no such file), '/usr/local/lib/libavutil.57.dylib' (no such file), '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg4\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 108, in _find_versionsed_ffmpeg_extension\n",
      "    _load_lib(lib)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 94, in _load_lib\n",
      "    torch.ops.load_library(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py\", line 933, in load_library\n",
      "    ctypes.CDLL(path)\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: dlopen(/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib\n",
      "  Referenced from: <3B5A8336-9CE3-36F7-9A02-C2D6D54842BB> /Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so\n",
      "  Reason: tried: '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/lib/../../../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/lib-dynload/../../libavutil.56.dylib' (no such file), '/Users/timcares/miniconda3/envs/mmrl_/bin/../lib/libavutil.56.dylib' (no such file), '/usr/local/lib/libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)\n",
      "DEBUG:torio._extension.utils:Loading FFmpeg\n",
      "DEBUG:torio._extension.utils:Failed to load FFmpeg extension.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 116, in _find_ffmpeg_extension\n",
      "    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py\", line 106, in _find_versionsed_ffmpeg_extension\n",
      "    raise RuntimeError(f\"FFmpeg{version} extension is not available.\")\n",
      "RuntimeError: FFmpeg extension is not available.\n"
     ]
    }
   ],
   "source": [
    "_, result = callback.on_validation_start(trainer=None, pl_module=pl_module)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "mmrl",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
